image: node:8.11.4

pipelines:
  default:
    - step:
        name: test
        deployment: test
        script:
            - cd api
            - npm install
            - npm run test
            - cd ../frontent
            - npm install
            - npm run test
#  branches:
#    master:
#      - step:
#          name: test
#          script:
#            - cd api
#            - npm install
#            - npm run test
#            - cd ../frontent
#            - npm install
#            - npm run test
#      - step:
#          name: build & deploy
#          deployment: production
#          services:
#            - docker
#          script:
#            - 