version: '3'
services:
  frontend-test:
    build:
      dockerfile: Dockerfile.test
  frontend:
    build:
      dockerfile: Dockerfile.prod
      encrypted_args_file: build-args.encrypted
  codeshipgcrdockercfg:
    image: codeship/gcr-dockercfg-generator
    encrypted_env_file: gcp-env.encrypted
    add_docker: true
  codeshipgceservice:
    image: codeship/google-cloud-deployment
    encrypted_env_file: gcp-env.encrypted
    add_docker: true
    working_dir: /deploy
    volumes:
      - ./:/deploy