ARG NODE_VER

# build
FROM node:$NODE_VER

WORKDIR /usr/app
COPY ./ ./

RUN npm install --no-progress --ignore-optional

ARG NODE_ENV
ARG PORT
ARG API_URL

RUN NODE_ENV=$NODE_ENV PORT=$PORT API_URL=$API_URL npm run build

# run
FROM node:$NODE_VER
COPY --from=0 /usr/app/dist ./
COPY package-lock.json package.json ./

RUN npm install --no-progress --production
CMD npm run start:prod