FROM node:8.11.4

WORKDIR /usr/app

COPY ./ ./
RUN npm install --no-progress --ignore-optional
RUN npm run build

FROM node:8.11.4
COPY --from=0 /usr/app/dist ./
COPY package-lock.json package.json ./
RUN npm install --no-progress --production
RUN npm start
