apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: boilerplate-spa
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: boilerplate-spa
    tier: frontend