apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: boilerplate-spa
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: boilerplate-spa
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: boilerplate-spa-frontend
          image: ataquino/boilerplate-spa-frontend
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NODE_ENV
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: API_URL
